# dev: log4jdbc \ub4dc\ub77c\uc774\ubc84 \uc0ac\uc6a9
db.driver=${DB_DRIVER:net.sf.log4jdbc.sql.jdbcapi.DriverSpy}
db.url=${DB_URL:jdbc:log4jdbc:oracle:thin:@localhost:1521/admin}
db.username=${DB_USERNAME:admin_dev}
db.password=${DB_PASSWORD:change-me}

db.initialSize=3
db.maxActive=20
db.maxIdle=5
db.minIdle=3
