CREATE TABLE ADM_USER_MST (
    USER_SEQ         NUMBER(19,0)      NOT NULL,
    LOGIN_ID         VARCHAR2(100)     NOT NULL,
    USER_NM          VARCHAR2(100)     NOT NULL,
    PWD_HASH         VARCHAR2(255)     NOT NULL,
    DEPT_SEQ         NUMBER(19,0),
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    LOGIN_FAIL_CNT   NUMBER(5,0) DEFAULT 0 NOT NULL,
    LOCK_YN          CHAR(1) DEFAULT 'N' NOT NULL,
    PWD_RESET_YN     CHAR(1) DEFAULT 'N' NOT NULL,
    LOCK_UNTIL_AT    TIMESTAMP(6),
    LAST_LOGIN_AT    TIMESTAMP(6),
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_USER_MST PRIMARY KEY (USER_SEQ),
    CONSTRAINT UK_ADM_USER_MST_01 UNIQUE (LOGIN_ID),
    CONSTRAINT CK_ADM_USER_MST_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_ADM_USER_MST_LOCK_YN CHECK (LOCK_YN IN ('Y', 'N')),
    CONSTRAINT CK_ADM_USER_MST_PWD_RESET CHECK (PWD_RESET_YN IN ('Y', 'N'))
);

CREATE TABLE ADM_AUTH_GROUP (
    AUTH_GROUP_SEQ   NUMBER(19,0)      NOT NULL,
    AUTH_GROUP_CD    VARCHAR2(100)     NOT NULL,
    AUTH_GROUP_NM    VARCHAR2(100)     NOT NULL,
    AUTH_GROUP_DESC  VARCHAR2(500),
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_AUTH_GROUP PRIMARY KEY (AUTH_GROUP_SEQ),
    CONSTRAINT UK_ADM_AUTH_GROUP_01 UNIQUE (AUTH_GROUP_CD),
    CONSTRAINT CK_ADM_AUTH_GROUP_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE ADM_MENU_MST (
    MENU_SEQ         NUMBER(19,0)      NOT NULL,
    UP_MENU_SEQ      NUMBER(19,0),
    MENU_NM          VARCHAR2(100)     NOT NULL,
    MENU_URL         VARCHAR2(300),
    MENU_TYPE_CD     VARCHAR2(30),
    ICON_CLASS       VARCHAR2(100),
    SORT_ORD         NUMBER(10,0) DEFAULT 0 NOT NULL,
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_MENU_MST PRIMARY KEY (MENU_SEQ),
    CONSTRAINT CK_ADM_MENU_MST_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT FK_ADM_MENU_MST_PARENT FOREIGN KEY (UP_MENU_SEQ) REFERENCES ADM_MENU_MST (MENU_SEQ)
);

CREATE TABLE ADM_AUTH_GROUP_USER (
    AUTH_GROUP_SEQ   NUMBER(19,0)      NOT NULL,
    USER_SEQ         NUMBER(19,0)      NOT NULL,
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_AUTH_GROUP_USER PRIMARY KEY (AUTH_GROUP_SEQ, USER_SEQ),
    CONSTRAINT CK_ADM_AUTH_GROUP_USER_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT FK_ADM_AUTH_GROUP_USER_GRP FOREIGN KEY (AUTH_GROUP_SEQ) REFERENCES ADM_AUTH_GROUP (AUTH_GROUP_SEQ),
    CONSTRAINT FK_ADM_AUTH_GROUP_USER_USR FOREIGN KEY (USER_SEQ) REFERENCES ADM_USER_MST (USER_SEQ)
);

CREATE TABLE ADM_AUTH_GROUP_DEPT (
    AUTH_GROUP_SEQ   NUMBER(19,0)      NOT NULL,
    DEPT_SEQ         NUMBER(19,0)      NOT NULL,
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_AUTH_GROUP_DEPT PRIMARY KEY (AUTH_GROUP_SEQ, DEPT_SEQ),
    CONSTRAINT CK_ADM_AUTH_GROUP_DEPT_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT FK_ADM_AUTH_GROUP_DEPT_GRP FOREIGN KEY (AUTH_GROUP_SEQ) REFERENCES ADM_AUTH_GROUP (AUTH_GROUP_SEQ)
);

CREATE TABLE ADM_AUTH_MENU (
    AUTH_GROUP_SEQ   NUMBER(19,0)      NOT NULL,
    MENU_SEQ         NUMBER(19,0)      NOT NULL,
    PERM_LVL         NUMBER(10,0) DEFAULT 0 NOT NULL,
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_AUTH_MENU PRIMARY KEY (AUTH_GROUP_SEQ, MENU_SEQ),
    CONSTRAINT CK_ADM_AUTH_MENU_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT FK_ADM_AUTH_MENU_GRP FOREIGN KEY (AUTH_GROUP_SEQ) REFERENCES ADM_AUTH_GROUP (AUTH_GROUP_SEQ),
    CONSTRAINT FK_ADM_AUTH_MENU_MENU FOREIGN KEY (MENU_SEQ) REFERENCES ADM_MENU_MST (MENU_SEQ)
);

CREATE TABLE ADM_AUTH_USER (
    USER_SEQ         NUMBER(19,0)      NOT NULL,
    MENU_SEQ         NUMBER(19,0)      NOT NULL,
    ACCESS_YN        CHAR(1) DEFAULT 'Y' NOT NULL,
    PERM_LVL         NUMBER(10,0) DEFAULT 0 NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_AUTH_USER PRIMARY KEY (USER_SEQ, MENU_SEQ),
    CONSTRAINT CK_ADM_AUTH_USER_ACCESS_YN CHECK (ACCESS_YN IN ('Y', 'N', 'X')),
    CONSTRAINT FK_ADM_AUTH_USER_USR FOREIGN KEY (USER_SEQ) REFERENCES ADM_USER_MST (USER_SEQ),
    CONSTRAINT FK_ADM_AUTH_USER_MENU FOREIGN KEY (MENU_SEQ) REFERENCES ADM_MENU_MST (MENU_SEQ)
);

CREATE TABLE ADM_CODE_MST (
    CODE_SEQ         NUMBER(19,0)      NOT NULL,
    CODE_GRP_CD      VARCHAR2(100)     NOT NULL,
    CODE_CD          VARCHAR2(100)     NOT NULL,
    CODE_NM          VARCHAR2(200)     NOT NULL,
    CODE_DESC        VARCHAR2(1000),
    SORT_ORD         NUMBER(10,0) DEFAULT 0 NOT NULL,
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_CODE_MST PRIMARY KEY (CODE_SEQ),
    CONSTRAINT UK_ADM_CODE_MST_01 UNIQUE (CODE_GRP_CD, CODE_CD),
    CONSTRAINT CK_ADM_CODE_MST_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE ADM_NOTI_MST (
    NOTI_SEQ         NUMBER(19,0)      NOT NULL,
    NOTI_TYPE_CD     VARCHAR2(30),
    TITLE            VARCHAR2(300)     NOT NULL,
    CONTENT          CLOB,
    START_DT         DATE,
    END_DT           DATE,
    PIN_YN           CHAR(1) DEFAULT 'N' NOT NULL,
    POPUP_YN         CHAR(1) DEFAULT 'N' NOT NULL,
    VIEW_CNT         NUMBER(19,0) DEFAULT 0 NOT NULL,
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_NOTI_MST PRIMARY KEY (NOTI_SEQ),
    CONSTRAINT CK_ADM_NOTI_MST_PIN_YN CHECK (PIN_YN IN ('Y', 'N')),
    CONSTRAINT CK_ADM_NOTI_MST_POPUP_YN CHECK (POPUP_YN IN ('Y', 'N')),
    CONSTRAINT CK_ADM_NOTI_MST_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE ADM_TIMELINE_MST (
    TIMELINE_SEQ     NUMBER(19,0)      NOT NULL,
    TIMELINE_TYPE_CD VARCHAR2(30),
    TITLE            VARCHAR2(300)     NOT NULL,
    CONTENT          CLOB,
    EVENT_DT         DATE              NOT NULL,
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_TIMELINE_MST PRIMARY KEY (TIMELINE_SEQ),
    CONSTRAINT CK_ADM_TIMELINE_MST_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE ADM_LOGIN_SESN (
    SESN_SEQ         NUMBER(19,0)      NOT NULL,
    SESSION_ID       VARCHAR2(64)      NOT NULL,
    USER_SEQ         NUMBER(19,0),
    LOGIN_ID         VARCHAR2(100)     NOT NULL,
    USER_NM          VARCHAR2(100),
    STATUS_CD        VARCHAR2(20)      NOT NULL,
    CLIENT_IP        VARCHAR2(45),
    USER_AGENT       VARCHAR2(500),
    LOGIN_AT         TIMESTAMP(6)      NOT NULL,
    LAST_ACCESS_AT   TIMESTAMP(6),
    EXPIRES_AT       TIMESTAMP(6),
    LOGOUT_AT        TIMESTAMP(6),
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_LOGIN_SESN PRIMARY KEY (SESN_SEQ),
    CONSTRAINT UK_ADM_LOGIN_SESN_01 UNIQUE (SESSION_ID),
    CONSTRAINT CK_ADM_LOGIN_SESN_STATUS CHECK (STATUS_CD IN ('ACTIVE', 'EXPIRED', 'REVOKED')),
    CONSTRAINT FK_ADM_LOGIN_SESN_USR FOREIGN KEY (USER_SEQ) REFERENCES ADM_USER_MST (USER_SEQ)
);

CREATE TABLE ADM_LOGIN_HIST (
    HIST_SEQ         NUMBER(19,0)      NOT NULL,
    USER_SEQ         NUMBER(19,0),
    LOGIN_ID         VARCHAR2(100),
    USER_NM          VARCHAR2(100),
    RESULT_CD        VARCHAR2(30)      NOT NULL,
    RESULT_MSG       VARCHAR2(400),
    SESSION_ID       VARCHAR2(64),
    CLIENT_IP        VARCHAR2(45),
    USER_AGENT       VARCHAR2(500),
    LOGIN_AT         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_LOGIN_HIST PRIMARY KEY (HIST_SEQ),
    CONSTRAINT CK_ADM_LOGIN_HIST_RESULT CHECK (RESULT_CD IN ('SUCCESS', 'FAIL', 'LOGOUT', 'MYPAGE_UPDATE', 'MYPAGE_PASSWORD_CHANGE')),
    CONSTRAINT FK_ADM_LOGIN_HIST_USR FOREIGN KEY (USER_SEQ) REFERENCES ADM_USER_MST (USER_SEQ)
);

CREATE TABLE ADM_REFRESH_TOKEN (
    REFRESH_SEQ      NUMBER(20,0)      NOT NULL,
    USER_SEQ         NUMBER(20,0)      NOT NULL,
    LOGIN_ID         VARCHAR2(100)     NOT NULL,
    SESSION_ID       VARCHAR2(64)      NOT NULL,
    TOKEN_HASH       VARCHAR2(64)      NOT NULL,
    EXPIRES_AT       TIMESTAMP(6)      NOT NULL,
    REVOKED_YN       CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100),
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_REFRESH_TOKEN PRIMARY KEY (REFRESH_SEQ),
    CONSTRAINT CK_ADM_REFRESH_TOKEN_REVOKE CHECK (REVOKED_YN IN ('Y', 'N')),
    CONSTRAINT FK_ADM_REFRESH_TOKEN_USR FOREIGN KEY (USER_SEQ) REFERENCES ADM_USER_MST (USER_SEQ)
);

CREATE TABLE ADM_API_MST (
    API_SEQ          NUMBER(19,0)      NOT NULL,
    API_TYPE         VARCHAR2(20)      NOT NULL,
    API_NM           VARCHAR2(200)     NOT NULL,
    CALLER_ID        VARCHAR2(100)     NOT NULL,
    TARGET_SERVICE   VARCHAR2(100)     NOT NULL,
    HTTP_METHOD      VARCHAR2(10)      NOT NULL,
    API_PATTERN      VARCHAR2(500)     NOT NULL,
    AUTH_TYPE        VARCHAR2(30)      NOT NULL,
    API_DESC         VARCHAR2(1000),
    USE_YN           CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100) NOT NULL,
    UPDATED_AT       TIMESTAMP(6),
    UPDATED_BY       VARCHAR2(100),
    CONSTRAINT PK_ADM_API_MST PRIMARY KEY (API_SEQ),
    CONSTRAINT CK_ADM_API_MST_TYPE CHECK (API_TYPE IN ('EXTERNAL', 'INTERNAL')),
    CONSTRAINT CK_ADM_API_MST_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE SEQUENCE ADM_USER_MST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_AUTH_GROUP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_MENU_MST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_CODE_MST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_NOTI_MST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_TIMELINE_MST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_LOGIN_SESN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_LOGIN_HIST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_REFRESH_TOKEN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADM_API_MST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_ADM_MENU_MST_01 ON ADM_MENU_MST (UP_MENU_SEQ, SORT_ORD, MENU_SEQ);
CREATE INDEX IDX_ADM_AUTH_GROUP_USER_01 ON ADM_AUTH_GROUP_USER (USER_SEQ, USE_YN);
CREATE INDEX IDX_ADM_AUTH_GROUP_DEPT_01 ON ADM_AUTH_GROUP_DEPT (DEPT_SEQ, USE_YN);
CREATE INDEX IDX_ADM_AUTH_MENU_01 ON ADM_AUTH_MENU (MENU_SEQ, USE_YN, PERM_LVL);
CREATE INDEX IDX_ADM_AUTH_USER_01 ON ADM_AUTH_USER (MENU_SEQ, ACCESS_YN);
CREATE INDEX IDX_ADM_CODE_MST_01 ON ADM_CODE_MST (CODE_GRP_CD, SORT_ORD, CODE_SEQ);
CREATE INDEX IDX_ADM_NOTI_MST_01 ON ADM_NOTI_MST (PIN_YN, START_DT DESC, NOTI_SEQ DESC);
CREATE INDEX IDX_ADM_TIMELINE_MST_01 ON ADM_TIMELINE_MST (EVENT_DT DESC, TIMELINE_SEQ DESC);
CREATE INDEX IDX_ADM_LOGIN_SESN_01 ON ADM_LOGIN_SESN (LOGIN_ID, STATUS_CD, LOGIN_AT DESC);
CREATE INDEX IDX_ADM_LOGIN_HIST_01 ON ADM_LOGIN_HIST (LOGIN_ID, LOGIN_AT DESC);
CREATE INDEX IDX_ADM_REFRESH_TOKEN_01 ON ADM_REFRESH_TOKEN (TOKEN_HASH, REVOKED_YN, EXPIRES_AT);
CREATE INDEX IDX_ADM_REFRESH_TOKEN_02 ON ADM_REFRESH_TOKEN (SESSION_ID, REVOKED_YN);
CREATE INDEX IDX_ADM_API_MST_01 ON ADM_API_MST (API_TYPE, USE_YN, API_SEQ DESC);
CREATE INDEX IDX_ADM_API_MST_02 ON ADM_API_MST (CALLER_ID, TARGET_SERVICE, HTTP_METHOD);
