# Dev example
# DB_DRIVER=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
# DB_URL=jdbc:log4jdbc:oracle:thin:@localhost:1521/admin
# DB_USERNAME=ADMIN_DEV

db.driver=${DB_DRIVER:net.sf.log4jdbc.sql.jdbcapi.DriverSpy}
db.url=${DB_URL:jdbc:log4jdbc:oracle:thin:@localhost:1521/admin}
db.username=${DB_USERNAME:}
db.password=${DB_PASSWORD:}

db.initialSize=${DB_INITIAL_SIZE:3}
db.maxActive=${DB_MAX_ACTIVE:20}
db.maxIdle=${DB_MAX_IDLE:5}
db.minIdle=${DB_MIN_IDLE:3}
