DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_cnt
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ADM_REFRESH_TOKEN';

    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ADM_REFRESH_TOKEN (
                REFRESH_SEQ NUMBER(20,0) PRIMARY KEY,
                USER_SEQ NUMBER(20,0) NOT NULL,
                LOGIN_ID VARCHAR2(100) NOT NULL,
                SESSION_ID VARCHAR2(64) NOT NULL,
                TOKEN_HASH VARCHAR2(64) NOT NULL,
                EXPIRES_AT TIMESTAMP(6) NOT NULL,
                REVOKED_YN CHAR(1) DEFAULT ''N'' NOT NULL,
                CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CREATED_BY VARCHAR2(100),
                UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATED_BY VARCHAR2(100)
            )';
    END IF;
END;
/

DECLARE
    v_cnt NUMBER;
    v_start NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_cnt
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = 'ADM_REFRESH_TOKEN_SEQ';

    IF v_cnt = 0 THEN
        SELECT NVL(MAX(REFRESH_SEQ), 0) + 1 INTO v_start
          FROM ADM_REFRESH_TOKEN;

        EXECUTE IMMEDIATE '
            CREATE SEQUENCE ADM_REFRESH_TOKEN_SEQ
            START WITH ' || v_start || '
            INCREMENT BY 1
            NOCACHE
            NOCYCLE';
    END IF;
END;
/

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_cnt
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'ADM_REFRESH_TOKEN_IX1';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX ADM_REFRESH_TOKEN_IX1 ON ADM_REFRESH_TOKEN (TOKEN_HASH, REVOKED_YN, EXPIRES_AT)';
    END IF;

    SELECT COUNT(1) INTO v_cnt
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'ADM_REFRESH_TOKEN_IX2';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX ADM_REFRESH_TOKEN_IX2 ON ADM_REFRESH_TOKEN (SESSION_ID, REVOKED_YN)';
    END IF;
END;
/
