DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_cnt
      FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'ADM_USER_MST'
       AND COLUMN_NAME = 'LOGIN_FAIL_CNT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ADM_USER_MST ADD LOGIN_FAIL_CNT NUMBER(5,0) DEFAULT 0 NOT NULL';
    END IF;

    SELECT COUNT(1) INTO v_cnt
      FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'ADM_USER_MST'
       AND COLUMN_NAME = 'LOCK_UNTIL_AT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ADM_USER_MST ADD LOCK_UNTIL_AT TIMESTAMP(6)';
    END IF;

    SELECT COUNT(1) INTO v_cnt
      FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'ADM_USER_MST'
       AND COLUMN_NAME = 'LOCK_YN';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ADM_USER_MST ADD LOCK_YN CHAR(1) DEFAULT ''N'' NOT NULL';
    END IF;

    SELECT COUNT(1) INTO v_cnt
      FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'ADM_USER_MST'
       AND COLUMN_NAME = 'LAST_LOGIN_AT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ADM_USER_MST ADD LAST_LOGIN_AT TIMESTAMP(6)';
    END IF;

    SELECT COUNT(1) INTO v_cnt
      FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'ADM_USER_MST'
       AND COLUMN_NAME = 'PWD_RESET_YN';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ADM_USER_MST ADD PWD_RESET_YN CHAR(1) DEFAULT ''N'' NOT NULL';
    END IF;
END;
/

DECLARE
    v_cnt NUMBER;
    v_start NUMBER;
BEGIN
    SELECT COUNT(1) INTO v_cnt
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = 'ADM_USER_MST_SEQ';

    IF v_cnt = 0 THEN
        SELECT NVL(MAX(USER_SEQ), 0) + 1 INTO v_start
          FROM ADM_USER_MST;

        EXECUTE IMMEDIATE '
            CREATE SEQUENCE ADM_USER_MST_SEQ
            START WITH ' || v_start || '
            INCREMENT BY 1
            NOCACHE
            NOCYCLE';
    END IF;
END;
/
